upgrade charm to v2.0-alpha.6
canonical/kfp-operators pull request #153
Opened 2023-02-08 11:32 UTC by NohaIhab

## Summary:

- bumped image from v2.0.0-alpha.5 to v2.0.0-alpha.6
- added SIMULATE_CAN_CONNECT = TRUE to unit tests to get rid of warnings

2023-02-08 14:54 UTC, DnPlas commented on charms/kfp-api/tests/unit/test_operator.py
> +ops.testing.SIMULATE_CAN_CONNECT = True
What's the need for this line?

2023-02-08 15:00 UTC, DnPlas commented
Thanks @NohaIhab, I am not so sure why you picked that PR in the description to base all your changes, but it would be preferable if you base your upgrade in the [1.7.0.rc.0](https://github.com/kubeflow/manifests/tree/v1.7.0-rc.0/apps/pipeline/upstream) branch in kubeflow/manifests. Can you confirm that those manifests/versions/etc. are the same as ours?

2023-02-08 16:45 UTC, ca-scribner requested changes
Most of this looks good, but I think the sync.py part needs work.  A number of the changes in this PR revert intentional differences we've introduced to depart from what upstream does.  

Are you sure that sync.py has changed between 1.6.1 and 1.7?  I don't see any changes, but I might be looking at the wrong thing

2023-02-10 21:21 UTC, ca-scribner commented on charms/kfp-profile-controller/files/upstream/sync.py
> +    main()
```suggestion
    main()

```

2023-02-10 21:22 UTC, ca-scribner approved these changes
lgtm!

2023-02-10 21:22 UTC, merged