Kf 4262 contributing
canonical/kfp-operators pull request #313
Opened 2023-08-29 09:57 UTC by ColmBhandal

Added contributing files for all KFP charms.

Content is generic.

2023-09-01 10:23 UTC, phoevos requested changes
Thanks @ColmBhandal, some changes.
Note, that we should also rerender the `contributing.md` files based on the change introduced [here](https://github.com/canonical/kubeflow-ci/pull/107), in order to avoid a follow-up PR.

2023-09-01 10:23 UTC, phoevos commented on charms/kfp-api/contributing_inputs.yaml
> +  1. Ensure integration and unit tests are passing; fix/adapt them otherwise
Let's add a new line at the end of the file, please.

2023-09-01 10:23 UTC, phoevos commented on charms/kfp-persistence/contributing_inputs.yaml
> +  1. Ensure integration and unit tests are passing; fix/adapt them otherwise
Let's add a new line at the end of the file, please.

2023-09-01 10:23 UTC, phoevos commented on charms/kfp-profile-controller/contributing_inputs.yaml
> +  1. Ensure integration and unit tests are passing; fix/adapt them otherwise
Let's add a new line at the end of the file, please.

2023-09-01 10:23 UTC, phoevos commented on charms/kfp-schedwf/contributing_inputs.yaml
> +  1. Ensure integration and unit tests are passing; fix/adapt them otherwise
Let's add a new line at the end of the file, please.

2023-09-01 10:23 UTC, phoevos commented on charms/kfp-ui/contributing_inputs.yaml
> +  1. Ensure integration and unit tests are passing; fix/adapt them otherwise
Let's add a new line at the end of the file, please.

2023-09-01 10:23 UTC, phoevos commented on charms/kfp-viewer/contributing_inputs.yaml
> +  1. Ensure integration and unit tests are passing; fix/adapt them otherwise
Let's add a new line at the end of the file, please.

2023-09-01 10:23 UTC, phoevos commented on charms/kfp-viz/contributing_inputs.yaml
> +  1. Ensure integration and unit tests are passing; fix/adapt them otherwise
Let's add a new line at the end of the file, please.

2023-09-01 10:23 UTC, phoevos commented on charms/kfp-viewer/contributing_inputs.yaml
> +    --resource oci-image=$(yq '.resources."oci-image"."upstream-source"' metadata.yaml)
See: https://github.com/canonical/kfp-operators/blob/38fd0f0d8ae5a6195930add44543700986bfc891/charms/kfp-viewer/metadata.yaml#L11-L15
```suggestion
    --resource oci-image=$(yq '.resources."kfp-viewer-image"."upstream-source"' metadata.yaml)
```

2023-09-01 10:23 UTC, phoevos commented on charms/kfp-viewer/contributing_inputs.yaml
> +    --resource oci-image=$(yq '.resources."oci-image"."upstream-source"' metadata.yaml)
Then please rerender `contributing.md`.

2023-09-01 10:23 UTC, phoevos commented on charms/kfp-ui/contributing_inputs.yaml
> +    --resource oci-image=$(yq '.resources."oci-image"."upstream-source"' metadata.yaml)
See: https://github.com/canonical/kfp-operators/blob/38fd0f0d8ae5a6195930add44543700986bfc891/charms/kfp-ui/metadata.yaml#L9-L13

```suggestion
    --resource oci-image=$(yq '.resources."ml-pipeline-ui"."upstream-source"' metadata.yaml)
```

Then please rerender `contributing.md`.

2023-09-05 12:20 UTC, ColmBhandal commented
> Thanks @ColmBhandal, some changes. Note, that we should also rerender the `contributing.md` files based on the change introduced [here](https://github.com/canonical/kubeflow-ci/pull/107), in order to avoid a follow-up PR.

I'm working on fixing the automation. It should not result in a follow-up PR to `main`, but rather a PR targeting this branch which we can just merge. I just need to fix the issue that seems to be with permissions...

2023-09-05 14:17 UTC, ColmBhandal commented
Closing this as it's too much effort. We have decided for now to go with the simpler option of just manually creating and maintaining contributing files.

2023-09-05 14:17 UTC, closed without merging