Add prometheus integration
canonical/kfp-operators pull request #48
Opened 2022-01-24 21:25 UTC by phvalguima

Integrate with prometheus-k8s using prometheus_scrape interface
to submit a job. Prometheus should scrape the Pod IP on port
8888 by default to recover the metrics.

Moved to ops 1.3.0 to support prometheus_scrape.py interface.

2022-01-25 09:34 UTC, DomFleischmann reviewed
Thanks for the work on this @phvalguima ! I got one minor comment and also let @ca-scribner and @DnPlas review this.

2022-01-25 09:34 UTC, DomFleischmann commented on charms/kfp-api/src/charm.py
> +        self.framework.observe(self.on["monitoring"].relation_departed, self._main)
You can add these statements to the `for event in change_events:` loop.

2022-01-26 02:55 UTC, DnPlas commented
Thanks @phvalguima. I agree on @DomFleischmann's comment, other than that LGTM.

2022-02-01 06:13 UTC, grobbie requested changes

2022-02-01 06:13 UTC, grobbie commented on charms/kfp-api/tests/unit/test_operator.py
> +                "addresses": [{"hostname": "cassandra-tester-0", "value": bind_address}],
```suggestion
                "addresses": [{"hostname": "kubeflow-tester-0", "value": bind_address}],
```

2022-02-01 06:13 UTC, grobbie commented on charms/kfp-api/src/charm.py
> +                    "scrape_interval": "30s",
Scrape interval could be configurable with a 30s default

2022-03-17 13:37 UTC, DomFleischmann commented
This has been covered by #65

2022-03-17 13:37 UTC, closed without merging