chore: Upgrade manifests to 2.3.0
canonical/kfp-operators pull request #583
Opened 2024-11-13 16:33 UTC by orfeas-k

Upgrade manifests to 2.3.0. For producing the manifests, instructions in the [CONTRIBUTING.md](https://github.com/canonical/kfp-operators/blob/main/CONTRIBUTING.md) file were followed.

This includes:
* Upgrading images
* Updating kfp-api auth-manifests
* Introducing a new envvar in kfp-ui

Ref #580 (in order to closes this, we need to ~~backport this~~ cut a new branch)

2024-11-20 04:31 UTC, DnPlas reviewed
All changes LGTM, for testing this I deployed all kfp charms and checked the status, as well as their logs.
Since `kfp-ui` is the charm that received the most changes, I focused on it and inspected the pebble logs. While most of it looks normal, I noticed two things:

1. There is a `2024-11-20T04:12:03.662Z [ml-pipeline-ui] Failed reading json data from '/etc/config/viewer-pod-template.json':
2024-11-20T04:12:03.664Z [ml-pipeline-ui] SyntaxError: Unexpected end of JSON input` message.
2. There are a lot of warnings like `2024-11-20T04:12:03.686Z [ml-pipeline-ui] (node:15) Warning: Accessing non-existent property 'which' of module exports inside circular dependency`

I don't think any of this is affecting the charm, but it's worth double checking.

2024-11-20 07:34 UTC, orfeas-k commented
Hey @DnPlas, thank you for taking a thorough look. For the first one, I have already filed this issue https://github.com/canonical/kfp-operators/issues/603. This has been observed in `latest/edge` kfp-ui (without the upgrades) and I think it should be present in 1.9 too. Regarding 2, this is also present in `latest/edge` without the upgrades. Let me file an issue for this as well and we 'd need to investigate separately

2024-11-20 09:07 UTC, NohaIhab requested changes
Thanks @orfeas-k , `bundle-integration-v2` tests all passed locally
I can confirm the logs reported by @DnPlas do not affect the functionality

one thing missed: to upgrade the driver and launcher images in `config.yaml` of `kfp-api` charm

2024-11-20 15:12 UTC, orfeas-k commented
@NohaIhab Very good catch Noha. Updated the PR. Also, I 've opened #610 against the `dev` branch updating the contributing.md file.

2024-11-20 19:02 UTC, DnPlas approved these changes
LGTM, thanks @orfeas-k

2024-11-21 08:43 UTC, NohaIhab approved these changes

2024-11-21 11:32 UTC, merged